import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import './globals.css';
import Navbar from '@/components/Navbar';
import { SelectedKeywordsProvider } from '@/contexts/SelectedKeywordsContext'; // G.O.A.T. C.O.D.E.X. B.O.T. - Import provider

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='h-full'>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased h-full bg-slate-50 dark:bg-slate-900`}
      >
        <Navbar />
        <main className='py-8 px-4 sm:px-6 lg:px-8'>
          <SelectedKeywordsProvider>
            {' '}
            {/* G.O.A.T. C.O.D.E.X. B.O.T. - Wrap children with provider */}
            <div className='max-w-7xl mx-auto'>{children}</div>
          </SelectedKeywordsProvider>
        </main>
      </body>
    </html>
  );
}
