name: CI Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json' # Cache based on all lock files in the repo

      - name: Install Root Dependencies
        run: npm install

      - name: Install Frontend Dependencies
        run: npm install --prefix frontend

      - name: Install Backend Dependencies
        run: npm install --prefix backend

      - name: Run Linters (Frontend & Backend)
        run: npm run lint

      - name: Check Formatting (Frontend & Backend)
        run: npm run check-format

      - name: Run Backend Tests
        run: npm run test

      - name: Build Frontend
        run: npm run build --prefix frontend
